language: python
python:

  - "2.7.12"

services:
-postgresql
# command to install dependencies
#add section to create travis table
install:
  - pip install -r requirements.txt
  - psql -c 'create database fast_food;' -U postgres
  - python create_tables.py
# command to run tests
script: 
- pytest --cov=.
- coverage
- coveralls
after_success:
- coveralls
