language: python
python:

  - "2.7.12"
env:
- APP_SETTINGS=testing
services:
- postgresql
# command to install dependencies
#add section to create travis table
install:
  - pip install -r requirements.txt
before_script:
- psql -c 'create user francis with password atagenda1@;' -U postgres
- psql -c 'create database Fast_food_fast_testing;' -U  postgres
# command to run tests
script: 
- pytest --cov=.
- coverage
- coveralls
after_success:
- coveralls



