language: python
python:

  - "2.7.12"

services:
- postgresql
# command to install dependencies
#add section to create travis table
install:
  - pip install -r requirements.txt
before_script:
 - psql -c 'create database Fast_food_fast;'-U francis
# command to run tests
script: 
- pytest --cov=.
- coverage
- coveralls
after_success:
- coveralls
